//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMigration
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Data
    {
        [Key]
        public long MeasurementID { get; set; }
        public string Tag { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<long> LongValue { get; set; }
        public string TextValue { get; set; }
        public byte[] BinaryValue { get; set; }
        public string XmlValue { get; set; }
    
        public virtual Measurement Measurement { get; set; }
    }
}
